export const q1Boosts = [
  {
    optionKey: "changes",
    optionLabel: "I am going through big changes.",
    boosts: [
      { symbol: "Transformation", bonusWeight: 2 },
      { symbol: "Rebirth", bonusWeight: 2 },
      { symbol: "Reinvention", bonusWeight: 1 },
      { symbol: "Breakthrough", bonusWeight: 1 },
      { symbol: "Journey", bonusWeight: 1 },
      { symbol: "Surrender", bonusWeight: 1 },
      { symbol: "Vision", bonusWeight: 1 },
      { symbol: "Creativity", bonusWeight: 1 },
    ],
  },
  {
    optionKey: "powerful",
    optionLabel: "I feel powerful and ready to act.",
    boosts: [
      { symbol: "Power", bonusWeight: 2 },
      { symbol: "Action", bonusWeight: 2 },
      { symbol: "Courage", bonusWeight: 2 },
      { symbol: "Focus", bonusWeight: 1 },
      { symbol: "Willpower", bonusWeight: 1 },
      { symbol: "Leadership", bonusWeight: 1 },
      { symbol: "Strategy", bonusWeight: 1 },
    ],
  },
  {
    optionKey: "emotional",
    optionLabel: "I feel emotional or healing.",
    boosts: [
      { symbol: "Healing", bonusWeight: 2 },
      { symbol: "Compassion", bonusWeight: 2 },
      { symbol: "Forgiveness", bonusWeight: 2 },
      { symbol: "Grief", bonusWeight: 2 },
      { symbol: "Renewal", bonusWeight: 1 },
      { symbol: "Resilience", bonusWeight: 1 },
      { symbol: "Protection", bonusWeight: 1 },
      { symbol: "Boundaries", bonusWeight: 1 },
    ],
  },
  {
    optionKey: "clear",
    optionLabel: "I feel clear and focused.",
    boosts: [
      { symbol: "Vision", bonusWeight: 2 },
      { symbol: "Focus", bonusWeight: 2 },
      { symbol: "Discipline", bonusWeight: 1 },
      { symbol: "Truth", bonusWeight: 1 },
      { symbol: "Wisdom", bonusWeight: 1 },
      { symbol: "Alignment", bonusWeight: 1 },
    ],
  },
  {
    optionKey: "stuck",
    optionLabel: "I feel stuck and want something to shift.",
    boosts: [
      { symbol: "Breakthrough", bonusWeight: 2 },
      { symbol: "Journey", bonusWeight: 2 },
      { symbol: "Reinvention", bonusWeight: 1 },
      { symbol: "Transformation", bonusWeight: 1 },
      { symbol: "Courage", bonusWeight: 1 },
      { symbol: "Curiosity", bonusWeight: 1 },
    ],
  },
  {
    optionKey: "spiritual",
    optionLabel: "I feel spiritual and seeking answers.",
    boosts: [
      { symbol: "Sacredness", bonusWeight: 2 },
      { symbol: "Intuition", bonusWeight: 2 },
      { symbol: "Purpose", bonusWeight: 1 },
      { symbol: "Awakening", bonusWeight: 1 },
      { symbol: "Alignment", bonusWeight: 1 },
      { symbol: "Mystery", bonusWeight: 1 },
      { symbol: "Timelessness", bonusWeight: 1 },
    ],
  },
];
